[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build>=0.13",
    "cmake",
    "ninja",
    "mediapipe >= 0.8.9",
    "numpy >= 1.19.5",
    "opencv_contrib_python >= 4.5.4.60",
]
build-backend = "setuptools.build_meta"